-- 보호소에 몇 시에 입양이 가장 활발하게 일어났는지
-- 9시 부터 오후 7시 59분까지, 입양이 몇 건이나 발생했는지 조회
SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY TO_NUMBER(TO_CHAR(DATETIME,'HH24'))
HAVING TO_NUMBER(TO_CHAR(DATETIME,'HH24')) BETWEEN 9 AND 19
ORDER BY HOUR