-- 코드를 입력하세요
-- 2022년 5월에 예약한 환자수를 진료과코드 별로 조회
SELECT MCDP_CD AS "진료과코드",
       COUNT(APNT_NO) AS "5월예약건수"
  FROM APPOINTMENT
 WHERE 1=1 
 AND EXTRACT(YEAR FROM APNT_YMD) = 2022
  AND EXTRACT(MONTH FROM APNT_YMD) = 5
GROUP BY MCDP_CD
ORDER BY COUNT(APNT_NO) ASC, MCDP_CD ASC;