-- 코드를 입력하세요
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, 
TO_CHAR(B.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
WHERE A.BOARD_ID = B.BOARD_ID 
AND TRUNC(A.CREATED_DATE,'MONTH') = TO_DATE('2022-10-01',  'YYYY-MM-DD')
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;