-- 코드를 입력하세요
-- 2022년 1월의 카테고리 별 도서 판매량을 합산하고, 카테고리, 총판매량 리스트를 출력
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
  FROM BOOK B, BOOK_SALES S
 WHERE B.BOOK_ID = S.BOOK_ID
   AND TO_CHAR(SALES_DATE,'YYYY-MM') IN ('2022-01')
 GROUP BY CATEGORY
 ORDER BY CATEGORY;