-- 코드를 입력하세요
-- 각 아이스크림 성분 타입과 성분 타입에 대한 아이스크림의 총주문량 
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
  FROM FIRST_HALF, ICECREAM_INFO 
  WHERE FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;