-- 코드를 입력하세요
-- 각 아이스크림 성분 타입과 성분 타입에 대한 아이스크림의 총주문량 
SELECT I.INGREDIENT_TYPE, SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
  FROM FIRST_HALF F, ICECREAM_INFO I
  WHERE F.FLAVOR = I.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;